# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangePasswordGGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(268, 235)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.New_pass = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.New_pass.setFont(font)
        self.New_pass.setText("")
        self.New_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.New_pass.setObjectName("New_pass")
        self.gridLayout.addWidget(self.New_pass, 1, 0, 1, 1)
        self.Change_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Change_btn.setFont(font)
        self.Change_btn.setObjectName("Change_btn")
        self.gridLayout.addWidget(self.Change_btn, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.New_pass_repeat = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.New_pass_repeat.setFont(font)
        self.New_pass_repeat.setEchoMode(QtWidgets.QLineEdit.Password)
        self.New_pass_repeat.setObjectName("New_pass_repeat")
        self.gridLayout.addWidget(self.New_pass_repeat, 3, 0, 1, 1)
        self.Response = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Response.setFont(font)
        self.Response.setText("")
        self.Response.setAlignment(QtCore.Qt.AlignCenter)
        self.Response.setObjectName("Response")
        self.gridLayout.addWidget(self.Response, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.New_pass, self.New_pass_repeat)
        MainWindow.setTabOrder(self.New_pass_repeat, self.Change_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Change_btn.setText(_translate("MainWindow", "Change"))
        self.label_2.setText(_translate("MainWindow", "New Password:"))
        self.label.setText(_translate("MainWindow", "Repeat new Password:"))
